// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fit_gev
Rcpp::List fit_gev(Eigen::MatrixXd& data);
RcppExport SEXP _maxandsmooth_fit_gev(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_gev(data));
    return rcpp_result_gen;
END_RCPP
}
// ms_max
Rcpp::List ms_max(Eigen::MatrixXd& data, std::string& family);
RcppExport SEXP _maxandsmooth_ms_max(SEXP dataSEXP, SEXP familySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string& >::type family(familySEXP);
    rcpp_result_gen = Rcpp::wrap(ms_max(data, family));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_maxandsmooth_fit_gev", (DL_FUNC) &_maxandsmooth_fit_gev, 1},
    {"_maxandsmooth_ms_max", (DL_FUNC) &_maxandsmooth_ms_max, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_maxandsmooth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
