# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gev_mle <- function(data) {
    .Call(`_maxandsmooth_gev_mle`, data)
}

gev_mle_multiple <- function(data) {
    .Call(`_maxandsmooth_gev_mle_multiple`, data)
}

