# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_gev <- function(data) {
    .Call(`_maxandsmooth_fit_gev`, data)
}

ms_max <- function(data, family) {
    .Call(`_maxandsmooth_ms_max`, data, family)
}

